In [1]:
import pandas as pd
import numpy as np

# Load the thyroid dataset
df = pd.read_csv(
    r"../datasets/thyroid.csv"
)

# Dataset overview
print("Dataset shape:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

print("\nDataset information:")
df.info()

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Dataset shape: (383, 17)

Column names:
['Age', 'Gender', 'Smoking', 'Hx Smoking', 'Hx Radiothreapy', 'Thyroid Function', 'Physical Examination', 'Adenopathy', 'Pathology', 'Focality', 'Risk', 'T', 'N', 'M', 'Stage', 'Response', 'Recurred']

First 5 rows:

,Age,Gender,Smoking,Hx Smoking,Hx Radiothreapy,Thyroid Function,Physical Examination,Adenopathy,Pathology,Focality,Risk,T,N,M,Stage,Response,Recurred
0,27,F,No,No,No,Euthyroid,Single nodular goiter-left,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Indeterminate,No
1,34,F,No,Yes,No,Euthyroid,Multinodular goiter,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
2,30,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
3,62,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
4,62,F,No,No,No,Euthyroid,Multinodular goiter,No,Micropapillary,Multi-Focal,Low,T1a,N0,M0,I,Excellent,No

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 383 entries, 0 to 382
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   383 non-null    int64
 1   Gender                383 non-null    object
 2   Smoking               383 non-null    object
 3   Hx Smoking            383 non-null    object
 4   Hx Radiothreapy       383 non-null    object
 5   Thyroid Function      383 non-null    object
 6   Physical Examination  383 non-null    object
 7   Adenopathy            383 non-null    object
 8   Pathology             383 non-null    object
 9   Focality              383 non-null    object
 10  Risk                  383 non-null    object
 11  T                     383 non-null    object
 12  N                     383 non-null    object
 13  M                     383 non-null    object
 14  Stage                 383 non-null    object
 15  Response              383 non-null    object
 16  Recurred              383 non-null    object
dtypes: int64(1), object(16)
memory usage: 51.0+ KB

Missing values:
Age                     0
Gender                  0
Smoking                 0
Hx Smoking              0
Hx Radiothreapy         0
Thyroid Function        0
Physical Examination    0
Adenopathy              0
Pathology               0
Focality                0
Risk                    0
T                       0
N                       0
M                       0
Stage                   0
Response                0
Recurred                0
dtype: int64

Duplicate rows: 19

In [2]:
# 1. Check the target distribution
print("Target distribution:")
print(df["Recurred"].value_counts())

print("\nTarget distribution in percentage:")
print(
    (df["Recurred"].value_counts(normalize=True) * 100)
    .round(2)
)

# 2. Inspect the duplicate rows
print("\nNumber of duplicate rows:", df.duplicated().sum())

# 3. Check whether duplicate rows have conflicting targets
duplicate_rows = df[df.duplicated(keep=False)].sort_values(
    by=list(df.columns)
)

display(duplicate_rows.head(10))

Target distribution:
Recurred
No     275
Yes    108
Name: count, dtype: int64

Target distribution in percentage:
Recurred
No     71.8
Yes    28.2
Name: proportion, dtype: float64

Number of duplicate rows: 19

,Age,Gender,Smoking,Hx Smoking,Hx Radiothreapy,Thyroid Function,Physical Examination,Adenopathy,Pathology,Focality,Risk,T,N,M,Stage,Response,Recurred
136,21,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Papillary,Uni-Focal,Low,T2,N0,M0,I,Excellent,No
168,21,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Papillary,Uni-Focal,Low,T2,N0,M0,I,Excellent,No
161,22,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Papillary,Uni-Focal,Low,T2,N0,M0,I,Excellent,No
196,22,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Papillary,Uni-Focal,Low,T2,N0,M0,I,Excellent,No
106,26,F,No,No,No,Euthyroid,Multinodular goiter,No,Papillary,Uni-Focal,Low,T2,N0,M0,I,Excellent,No
121,26,F,No,No,No,Euthyroid,Multinodular goiter,No,Papillary,Uni-Focal,Low,T2,N0,M0,I,Excellent,No
138,26,F,No,No,No,Euthyroid,Multinodular goiter,No,Papillary,Uni-Focal,Low,T2,N0,M0,I,Excellent,No
183,26,F,No,No,No,Euthyroid,Multinodular goiter,No,Papillary,Uni-Focal,Low,T2,N0,M0,I,Excellent,No
119,28,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Papillary,Uni-Focal,Low,T2,N0,M0,I,Excellent,No
123,28,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Papillary,Uni-Focal,Low,T2,N0,M0,I,Excellent,No

In [3]:
# Find exact duplicate rows, including the first occurrence
duplicate_mask = df.duplicated(keep=False)
duplicate_df = df[duplicate_mask].sort_values(
    by=list(df.columns)
)

print("Rows involved in duplicate groups:", len(duplicate_df))

# Check whether identical feature values ever have different targets
feature_cols = [col for col in df.columns if col != "Recurred"]

label_counts = (
    df.groupby(feature_cols, dropna=False)["Recurred"]
      .nunique()
)

print(
    "Identical feature groups with conflicting targets:",
    (label_counts > 1).sum()
)

Rows involved in duplicate groups: 35
Identical feature groups with conflicting targets: 0

In [4]:
# Keep the original dataset unchanged
df_clean = df.drop_duplicates().copy()

print("Original dataset shape:", df.shape)
print("Cleaned dataset shape:", df_clean.shape)
print("Rows removed:", len(df) - len(df_clean))

print("\nTarget distribution after cleaning:")
print(df_clean["Recurred"].value_counts())

print("\nDuplicate rows remaining:", df_clean.duplicated().sum())

Original dataset shape: (383, 17)
Cleaned dataset shape: (364, 17)
Rows removed: 19

Target distribution after cleaning:
Recurred
No     256
Yes    108
Name: count, dtype: int64

Duplicate rows remaining: 0

In [5]:
# Separate input features and target
X = df_clean.drop(columns=["Recurred"])
y = df_clean["Recurred"]

print("Feature matrix shape:", X.shape)
print("Target vector shape:", y.shape)

print("\nFeature columns:")
print(X.columns.tolist())

print("\nTarget classes:")
print(y.unique())

print("\nTarget distribution:")
print(y.value_counts())

Feature matrix shape: (364, 16)
Target vector shape: (364,)

Feature columns:
['Age', 'Gender', 'Smoking', 'Hx Smoking', 'Hx Radiothreapy', 'Thyroid Function', 'Physical Examination', 'Adenopathy', 'Pathology', 'Focality', 'Risk', 'T', 'N', 'M', 'Stage', 'Response']

Target classes:
['No' 'Yes']

Target distribution:
Recurred
No     256
Yes    108
Name: count, dtype: int64

In [6]:
# Check how Response relates to the target
print("Response vs Recurred:")
display(pd.crosstab(
    df_clean["Response"],
    df_clean["Recurred"],
    margins=True
))

# Check target distribution for clinical staging features
for col in ["Risk", "T", "N", "M", "Stage"]:
    print(f"\n{col} vs Recurred:")
    display(pd.crosstab(
        df_clean[col],
        df_clean["Recurred"]
    ))

Response vs Recurred:

Recurred                 No  Yes  All
Response
Biochemical Incomplete   12   11   23
Excellent               188    1  189
Indeterminate            54    7   61
Structural Incomplete     2   89   91
All                     256  108  364

Risk vs Recurred:

Recurred       No  Yes
Risk
High            0   32
Intermediate   38   64
Low           218   12

T vs Recurred:

Recurred   No  Yes
T
T1a        45    1
T1b        35    5
T2        118   20
T3a        55   41
T3b         2   14
T4a         1   19
T4b         0    8

N vs Recurred:

Recurred   No  Yes
N
N0        222   27
N1a        12   10
N1b        22   71

M vs Recurred:

Recurred   No  Yes
M
M0        256   90
M1          0   18

Stage vs Recurred:

Recurred   No  Yes
Stage
I         249   65
II          7   25
III         0    4
IVA         0    3
IVB         0   11

In [7]:
# Exclude Response to reduce the risk of target leakage
X = df_clean.drop(columns=["Recurred", "Response"])
y = df_clean["Recurred"]

print("Feature matrix shape:", X.shape)
print("Target vector shape:", y.shape)

print("\nNumerical features:")
print(X.select_dtypes(include="number").columns.tolist())

print("\nCategorical features:")
print(X.select_dtypes(include="object").columns.tolist())

Feature matrix shape: (364, 15)
Target vector shape: (364,)

Numerical features:
['Age']

Categorical features:
['Gender', 'Smoking', 'Hx Smoking', 'Hx Radiothreapy', 'Thyroid Function', 'Physical Examination', 'Adenopathy', 'Pathology', 'Focality', 'Risk', 'T', 'N', 'M', 'Stage']

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

print("\nTraining target distribution:")
print(y_train.value_counts())

print("\nTesting target distribution:")
print(y_test.value_counts())

X_train shape: (291, 15)
X_test shape: (73, 15)

Training target distribution:
Recurred
No     205
Yes     86
Name: count, dtype: int64

Testing target distribution:
Recurred
No     51
Yes    22
Name: count, dtype: int64

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

# Identify numerical and categorical columns
numeric_features = X.select_dtypes(include="number").columns.tolist()
categorical_features = X.select_dtypes(include="object").columns.tolist()

# Preprocess numerical features
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

# Preprocess categorical features
categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

# Combine both preprocessing steps
preprocessor = ColumnTransformer(transformers=[
    ("num", numeric_transformer, numeric_features),
    ("cat", categorical_transformer, categorical_features)
])

print("Numerical features:", numeric_features)
print("Number of categorical features:", len(categorical_features))
print("Preprocessing pipeline created successfully.")

Numerical features: ['Age']
Number of categorical features: 14
Preprocessing pipeline created successfully.

In [10]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

models = {
    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        random_state=42
    ),
    "SVM": SVC(
        kernel="rbf",
        probability=True,
        random_state=42
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        class_weight="balanced"
    )
}

results = []

for name, model in models.items():
    # Combine preprocessing and classifier
    pipeline = Pipeline(steps=[
        ("preprocessor", preprocessor),
        ("classifier", model)
    ])

    # Train the model
    pipeline.fit(X_train, y_train)

    # Predict on unseen test data
    y_pred = pipeline.predict(X_test)

    # Calculate evaluation metrics
    results.append({
        "Model": name,
        "Accuracy": round(accuracy_score(y_test, y_pred) * 100, 2),
        "Precision": round(
            precision_score(y_test, y_pred, pos_label="Yes", zero_division=0) * 100, 2
        ),
        "Recall": round(
            recall_score(y_test, y_pred, pos_label="Yes", zero_division=0) * 100, 2
        ),
        "F1 Score": round(
            f1_score(y_test, y_pred, pos_label="Yes", zero_division=0) * 100, 2
        )
    })

    print(f"\n{'=' * 50}")
    print(name)
    print("=" * 50)
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred, labels=["No", "Yes"]))
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, zero_division=0))

results_df = pd.DataFrame(results)
print("\nMODEL COMPARISON")
print(results_df.to_string(index=False))

==================================================
Logistic Regression
==================================================
Confusion Matrix:
[[46  5]
 [ 6 16]]

Classification Report:
              precision    recall  f1-score   support

          No       0.88      0.90      0.89        51
         Yes       0.76      0.73      0.74        22

    accuracy                           0.85        73
   macro avg       0.82      0.81      0.82        73
weighted avg       0.85      0.85      0.85        73


==================================================
SVM
==================================================
Confusion Matrix:
[[46  5]
 [ 6 16]]

Classification Report:
              precision    recall  f1-score   support

          No       0.88      0.90      0.89        51
         Yes       0.76      0.73      0.74        22

    accuracy                           0.85        73
   macro avg       0.82      0.81      0.82        73
weighted avg       0.85      0.85      0.85        73


==================================================
Random Forest
==================================================
Confusion Matrix:
[[46  5]
 [ 6 16]]

Classification Report:
              precision    recall  f1-score   support

          No       0.88      0.90      0.89        51
         Yes       0.76      0.73      0.74        22

    accuracy                           0.85        73
   macro avg       0.82      0.81      0.82        73
weighted avg       0.85      0.85      0.85        73


MODEL COMPARISON
              Model  Accuracy  Precision  Recall  F1 Score
Logistic Regression     84.93      76.19   72.73     74.42
                SVM     84.93      76.19   72.73     74.42
      Random Forest     84.93      76.19   72.73     74.42

In [11]:
from sklearn.metrics import accuracy_score
import numpy as np

# Compare predictions from each trained pipeline
predictions = {}

for name, model in models.items():
    pipeline = Pipeline(steps=[
        ("preprocessor", preprocessor),
        ("classifier", model)
    ])

    pipeline.fit(X_train, y_train)
    predictions[name] = pipeline.predict(X_test)

print("Prediction comparison:")

model_names = list(predictions.keys())

for i in range(len(model_names)):
    for j in range(i + 1, len(model_names)):
        first = model_names[i]
        second = model_names[j]

        same = np.array_equal(
            predictions[first],
            predictions[second]
        )

        print(f"{first} vs {second}: Identical = {same}")

print("\nNumber of positive predictions:")
for name, pred in predictions.items():
    print(f"{name}: {(pred == 'Yes').sum()} Yes, {(pred == 'No').sum()} No")

Prediction comparison:
Logistic Regression vs SVM: Identical = False
Logistic Regression vs Random Forest: Identical = False
SVM vs Random Forest: Identical = False

Number of positive predictions:
Logistic Regression: 21 Yes, 52 No
SVM: 21 Yes, 52 No
Random Forest: 21 Yes, 52 No

In [12]:
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

comparison = []

for name, y_pred in predictions.items():
    tn, fp, fn, tp = confusion_matrix(
        y_test,
        y_pred,
        labels=["No", "Yes"]
    ).ravel()

    comparison.append({
        "Model": name,
        "Accuracy (%)": round(accuracy_score(y_test, y_pred) * 100, 2),
        "Recurrence Precision (%)": round(
            precision_score(y_test, y_pred, pos_label="Yes", zero_division=0) * 100, 2
        ),
        "Recurrence Recall (%)": round(
            recall_score(y_test, y_pred, pos_label="Yes", zero_division=0) * 100, 2
        ),
        "Recurrence F1 (%)": round(
            f1_score(y_test, y_pred, pos_label="Yes", zero_division=0) * 100, 2
        ),
        "True Negatives": tn,
        "False Positives": fp,
        "False Negatives": fn,
        "True Positives": tp
    })

comparison_df = pd.DataFrame(comparison)
print(comparison_df.to_string(index=False))

              Model  Accuracy (%)  Recurrence Precision (%)  Recurrence Recall (%)  Recurrence F1 (%)  True Negatives  False Positives  False Negatives  True Positives
Logistic Regression         84.93                     76.19                  72.73              74.42              46                5                6              16
                SVM         84.93                     76.19                  72.73              74.42              46                5                6              16
      Random Forest         84.93                     76.19                  72.73              74.42              46                5                6              16

In [13]:
import pandas as pd
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.pipeline import Pipeline
from sklearn.metrics import make_scorer, precision_score, recall_score, f1_score

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scoring = {
    "accuracy": "accuracy",
    "precision_yes": make_scorer(
        precision_score, pos_label="Yes", zero_division=0
    ),
    "recall_yes": make_scorer(
        recall_score, pos_label="Yes", zero_division=0
    ),
    "f1_yes": make_scorer(
        f1_score, pos_label="Yes", zero_division=0
    )
}

cv_results = []

for name, model in models.items():
    pipeline = Pipeline(steps=[
        ("preprocessor", preprocessor),
        ("classifier", model)
    ])

    scores = cross_validate(
        pipeline,
        X_train,
        y_train,
        cv=cv,
        scoring=scoring,
        n_jobs=-1
    )

    cv_results.append({
        "Model": name,
        "Accuracy Mean (%)": round(scores["test_accuracy"].mean() * 100, 2),
        "Accuracy Std (%)": round(scores["test_accuracy"].std() * 100, 2),
        "Precision Yes (%)": round(scores["test_precision_yes"].mean() * 100, 2),
        "Recall Yes (%)": round(scores["test_recall_yes"].mean() * 100, 2),
        "F1 Yes (%)": round(scores["test_f1_yes"].mean() * 100, 2)
    })

cv_results_df = pd.DataFrame(cv_results)
print(cv_results_df.to_string(index=False))

              Model  Accuracy Mean (%)  Accuracy Std (%)  Precision Yes (%)  Recall Yes (%)  F1 Yes (%)
Logistic Regression              87.62              2.56              79.16           80.13       79.24
                SVM              86.24              4.12              76.25           80.13       77.61
      Random Forest              87.61              5.30              83.44           74.25       77.92

In [14]:
import joblib
from pathlib import Path
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# Build the final pipeline
thyroid_model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(
        max_iter=2000,
        random_state=42
    ))
])

# Train using the complete training set
thyroid_model.fit(X_train, y_train)

# Final evaluation on the untouched test set
y_pred_final = thyroid_model.predict(X_test)

print("Final Model: Logistic Regression")
print(f"Test Accuracy: {accuracy_score(y_test, y_pred_final) * 100:.2f}%")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_final, labels=["No", "Yes"]))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_final, zero_division=0))

Final Model: Logistic Regression
Test Accuracy: 84.93%

Confusion Matrix:
[[46  5]
 [ 6 16]]

Classification Report:
              precision    recall  f1-score   support

          No       0.88      0.90      0.89        51
         Yes       0.76      0.73      0.74        22

    accuracy                           0.85        73
   macro avg       0.82      0.81      0.82        73
weighted avg       0.85      0.85      0.85        73

In [15]:
import joblib
from pathlib import Path

# Project model directory
model_dir = Path(r"E:\Multi_Disease_Prediction_System\models")
model_dir.mkdir(parents=True, exist_ok=True)

# Save the complete preprocessing + model pipeline
model_path = model_dir / "thyroid_recurrence_model.pkl"

joblib.dump(thyroid_model, model_path)

print("Model saved successfully!")
print("Model path:", model_path)
print("File exists:", model_path.exists())

Model saved successfully!
Model path: E:\Multi_Disease_Prediction_System\models\thyroid_recurrence_model.pkl
File exists: True

In [16]:
import joblib
import numpy as np
from pathlib import Path

model_path = Path(
    r"E:\Multi_Disease_Prediction_System\models\thyroid_recurrence_model.pkl"
)

# Load the saved pipeline
loaded_model = joblib.load(model_path)

# Predict using the reloaded model
saved_model_predictions = loaded_model.predict(X_test)

# Compare predictions with the original trained model
original_predictions = thyroid_model.predict(X_test)

print("Model loaded successfully:", model_path.exists())
print(
    "Predictions identical:",
    np.array_equal(original_predictions, saved_model_predictions)
)
print(
    "Saved model test accuracy:",
    f"{accuracy_score(y_test, saved_model_predictions) * 100:.2f}%"
)

Model loaded successfully: True
Predictions identical: True
Saved model test accuracy: 84.93%

In [17]:
# Select one actual record from the test set
sample_patient = X_test.iloc[[0]].copy()

print("Sample patient input:")
display(sample_patient)

# Predict recurrence
prediction = loaded_model.predict(sample_patient)[0]

# Get probability for each class
probabilities = loaded_model.predict_proba(sample_patient)[0]
class_labels = loaded_model.classes_

print("\nPrediction:", prediction)

print("\nClass probabilities:")
for label, probability in zip(class_labels, probabilities):
    print(f"{label}: {probability * 100:.2f}%")

Sample patient input:

,Age,Gender,Smoking,Hx Smoking,Hx Radiothreapy,Thyroid Function,Physical Examination,Adenopathy,Pathology,Focality,Risk,T,N,M,Stage
119,28,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Papillary,Uni-Focal,Low,T2,N0,M0,I

Prediction: No

Class probabilities:
No: 97.34%
Yes: 2.66%

In [18]:
# Expected features used during training
expected_features = loaded_model.feature_names_in_.tolist()

print("Number of expected features:", len(expected_features))
print("\nExpected feature names and order:")

for i, feature in enumerate(expected_features, start=1):
    print(f"{i}. {feature}")

print("\nSample input columns match:",
      sample_patient.columns.tolist() == expected_features)

Number of expected features: 15

Expected feature names and order:
1. Age
2. Gender
3. Smoking
4. Hx Smoking
5. Hx Radiothreapy
6. Thyroid Function
7. Physical Examination
8. Adenopathy
9. Pathology
10. Focality
11. Risk
12. T
13. N
14. M
15. Stage

Sample input columns match: True